name: User Microservice CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compile and Package (dev profile)
        run: mvn clean package -DskipTests

      - name: Run Unit and Functional Tests (test profile)
        run: mvn test

